
spring: 
  cloud: 
    stream: 
       kafka:
         binder:
           brokers:
             - localhost
           zk-nodes:            
             - localhost
       default:
         group: ${spring.application.name}
         consumer:     
           maxAttempts: 1
       bindings:
         requestIn:
           destination: ms.data
           group: request-audit
           content-type: application/json
         requestOut:
           destination: ms.data
           content-type: application/json
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring-cloud

    
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
    lease-renewal-interval-in-seconds: 30 
    lease-expiration-duration-in-seconds: 60
    status-page-url-path: ${server.context-path}/info
    health-check-url-path: ${server.context-path}/health
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
region: 
  name: Shanghai
  timeZone: Asia/Shanghai
  
origins: ALLOW_ALL


management:
  security:
    enabled: false
  health:
    defaults:
      enabled: true

ribbon:
  ConnectTimeout: 10000   
  ReadTimeout: 30000

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 30000
       
hystrix:
  command:  
    default:
      execution:
        isolation:
          semaphore:
            maxConcurrentRequests: 1500
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
      circuitBreaker:
        forceClosed: true
      fallback:
        enabled: true
        
logging:
  level:
    org.springframework.web: ERROR
    com.pwc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: "application.log"
  
